# Application CI/CD

name: Application CI/CD

on: [push, pull_request]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2.3.3
    
    - name: Setup NuGet
      uses: actions/setup-dotnet@v1.7.2
      
    - name: Restore NuGet packages
      run:  nuget restore WPFApp-GitHubActions.sln
      
    - name: Setup MSBuild and Build the solution
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build solution WPFApp-GitHubActions.sln
      run:  msbuild WPFApp-GitHubActions.sln /p:platform="Any CPU" /p:Configuration='Release'
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: WPFApp-GitHubActionsActions
        path: "WPFApp/bin/Release"