name: WPF .NET Application CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    env:
        Solution_Path: MyWpfApp.sln

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
         
    - name: Build Solution
      run: dotnet build $env:Solution_Path
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyApplication
        path: "WPFApp/bin/Release"