# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name: Example2.NetFramework.CI

on: [push]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.3.3
    


    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Restore NuGet packages
      run: nuget restore WPFApp-GitHubActions.sln
      
    - name: Setup MSBuild & Build the solution
      uses: microsoft/setup-msbuild@v1.0.2
      run: msbuild WPFApp-GitHubActions.sln /p:platform="Any CPU" /p:Configuration='Release'
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyApplication
        path: "WPFApp/bin/Release"  